In [1]:
from fplpandas import FPLPandas
import numpy as np
import pandas as pd

In [2]:
fpl = FPLPandas()

In [3]:
teams = fpl.get_teams()
teams

,code,draw,form,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
id,,,,,,,,,,,,,,,,,,,,
1,3,0,None,0,Arsenal,0,0,0,ARS,4,None,False,0,1200,1250,1130,1150,1220,1210,1
2,7,0,None,0,Aston Villa,0,0,0,AVL,3,None,False,0,1100,1160,1120,1140,1080,1100,2
3,36,0,None,0,Brighton,0,0,0,BHA,3,None,False,0,1130,1130,1150,1190,1100,1130,131
4,90,0,None,0,Burnley,0,0,0,BUR,2,None,False,0,1060,1070,1040,1090,1040,1080,43
5,8,0,None,0,Chelsea,0,0,0,CHE,4,None,False,0,1250,1280,1260,1300,1250,1310,4
6,31,0,None,0,Crystal Palace,0,0,0,CRY,3,None,False,0,1090,1110,1030,1120,1010,1020,6
7,11,0,None,0,Everton,0,0,0,EVE,3,None,False,0,1250,1130,1130,1100,1200,1140,7
8,54,0,None,0,Fulham,0,0,0,FUL,3,None,False,0,1090,1100,1150,1110,1040,1060,34
9,13,0,None,0,Leicester,0,0,0,LEI,4,None,False,0,1240,1260,1190,1150,1150,1230,26
10,2,0,None,0,Leeds,0,0,0,LEE,3,None,False,0,1160,1170,1060,1150,1210,1170,9
11,14,0,None,0,Liverpool,0,0,0,LIV,4,None,False,0,1250,1210,1190,1210,1300,1230,10
12,43,0,None,0,Man City,0,0,0,MCI,5,None,False,0,1340,1360,1280,1320,1340,1350,11
13,1,0,None,0,Man Utd,0,0,0,MUN,4,None,False,0,1250,1320,1250,1280,1240,1310,12
14,4,0,None,0,Newcastle,0,0,0,NEW,2,None,False,0,1050,1070,1050,1060,1030,1110,23
15,49,0,None,0,Sheffield Utd,0,0,0,SHU,2,None,False,0,1000,1040,1020,1070,1000,1010,18
16,20,0,None,0,Southampton,0,0,0,SOU,3,None,False,0,1060,1100,1030,1110,1110,1160,20
17,6,0,None,0,Spurs,0,0,0,TOT,4,None,False,0,1190,1250,1130,1170,1250,1290,21
18,35,0,None,0,West Brom,0,0,0,WBA,2,None,False,0,1050,1040,1040,1000,1050,1040,36
19,21,0,None,0,West Ham,0,0,0,WHU,4,None,False,0,1230,1260,1140,1190,1260,1290,25
20,39,0,None,0,Wolves,0,0,0,WOL,3,None,False,0,1080,1110,1120,1130,1040,1120,38

In [4]:
#player_summary, player_hist, player_fixtures, player_future = fpl.get_players()

In [5]:
player_dfs = fpl.get_players()

In [6]:
fixtures = fpl.get_fixtures()

In [7]:
#Clean the Player Summary Table
player_summary = player_dfs[0]
convert_dict = {'value_season': float} 
player_summary = player_summary.astype(convert_dict)
player_summary['team'] = player_summary.team_code.map(teams.set_index('code').name)

In [8]:
#Clean the Player Fixtures Table
player_fixtures = player_dfs[2]
convert_dict_fixture = {
    'element': int
}

player_lookup = player_summary[['web_name', 'element_type', 'team', 'minutes']]
team_lookup = teams[['name','strength']]
player_fixtures = player_fixtures.astype(convert_dict_fixture)

player_fixtures = pd.merge(player_fixtures, player_lookup, left_on='element', right_on='id', how='left')
player_fixtures = pd.merge(player_fixtures, team_lookup, left_on='opponent_team', right_on='id', how='left')
player_fixtures = player_fixtures[player_fixtures['minutes_y']>=0]

In [9]:
fixtures.to_csv('fixtures.csv')

In [10]:
player_summary[['web_name','ep_this','ep_next',"element_type"]].sort_values(by=["ep_next"], ascending=False).to_csv("adhoc_ep_this.csv")

In [11]:
player_summary.to_csv('player_summary.csv')

In [12]:
player_fixtures.to_csv('player_fixtures.csv')